### PR TITLE
Adding info about recommended instance size

### PR DESCRIPTION
**Pull request by z4nr34l**
On instances with less than 1GB of RAM (popular 512MB RAM smallest tier) MySQL is crashing and can get someone not experienced into trouble.

### CODE REVIEW

**Comment by Code-Egg** [comment]
Hi @Lexonouri , 

Thanks for the PR. 

I have a question about which CMS you have tried and got crashed due to low Memory. Because we have MySql pre-installed for WordPress and CyberPanel only. If we mention 1 GB as a minimum requirement may misleading Django, NodeJS...etc users.

**Comment by z4nr34l** [comment]
Yeah, that's true, I will try to reorganize it, as its important info only for WordPress installation script and images. Clean LSCP can work fine as it's not taking so much memory. I will update this PR after work.

**Comment by z4nr34l** [comment]
Ok, I removed it from main readme, please add this information above build process in https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image wiki page, I think that's just the right place for it.

**Comment by Code-Egg** [comment]
Sure, will do

**Pull request closed without merging**
